services:
  db:
    image: mysql:8.0
    container_name: mysql
    # A porta NÃO está exposta para o host (não tem a chave 'ports')
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - todo-mysql-data:/var/lib/mysql
    networks:
      - todo-net
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    #build: .
    container_name: todo
    ports:
      - "3000:3000"
    environment:
      MYSQL_HOST: db # Aponta para o nome do serviço do banco acima
      MYSQL_USER: root
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DB: ${MYSQL_DATABASE}
    networks:
      - todo-net
    depends_on:
      db:
        condition: service_healthy

# Rede nomeada explicitamente
networks:
  todo-net:
    name: todo-net

# Volume nomeado para persistência dos dados
volumes:
  todo-mysql-data:
    name: todo-mysql-data